# 예외 처리

<mark>**java에서 예외(Exception)은 사용자의 잘못된 조작이나 개발자의 실수로 인해 발생하는 프로그램 오류를 말함**</mark>

우리는 **예외 처리**를 통해서 실행 중인 프로그램의 갑작스런 비정상적인 동작을 막고, 에러를 잡아 복구하거나 회피 하는 방법으로 **프로그램이 정상적인 실행상태를 유지**할 수 있도록 한다.

java에서 Excpetion class는 java.lang.Exception 클래스를 상속받는다.



</br>


## 1️⃣ UnCkecked Exception & Checked Exception

- **Checked Exception**(일반 예외) : 컴파일 시점에 확인되며, 반드시 처리해야 하는 예외 (개발자가 직접 예외 처리를 직접 진행)
- **UnChecked Exception**(실행 예외) : 런타임 시점에 발생하는 예외, 개발자에게 예외 처리를 강제하지 않음, 일반적으로 RuntimeException들은 UnChecked이다. (ex : NullPointerException, ArrayIndexOutOfBoundsException, NumberFormatException 등)



</br>


## 2️⃣ 예외 처리 코드(try ~ catch ~ finally)

```java
try{
// 예외가 발생할 가능성이 있는 코드
//예외 발생 시, 바로 catch 문으로 이동

}
catch(Exception ex){
  // 예외 처리
}
finally{
  //무슨 일이 있어도 반드시 실행
}

```

</br>

다중 catch문 

```java
try{
   // NumberFormatException 발생 코드
   // Exception 발생 코드
}
catch(NumberFormatException ex){
}
catch(Exception ex){
}

```

NumberFormatException 발생 시, Exception 발생 코드는 실행하지 않고 바로 NumberFormatException catch 문으로 이동한다. 이 때문에 다중 catch문을 작성할 경우, **상위 예외 클래스가 하위 예외 클래스보다 밑에 위치하게 작성**해야 한다. (여기서는 Exception이 상위 예외 클래스)


</br>


## 3️⃣ 멀티 catch 문

JAVA 7 부터는 catch 블록에서 여러 개의 예외를 처리할 수가 있다. 

```java
try{

}
catch(NumberFormatException | FileNotFoundException ex){
}
catch(Exception ex){
}

```



</br>

## 4️⃣ 예외 메세지 출력

1. <code>printStackTrace()</code> : 예외발생 당시의 호출스택(Call Stack)에 있었던 메서드의 정보와 예외 메시지를  출력 
2. <code>getMessage()</code> : 발생한 예외클래스의 인스턴스에 저장된 메시지 출력

</br>

|Error & Exception|
|------|
|**Error** : 수습할 수 없는 심각한 문제 </br> **Exception** : 개발자가 구현한 로직에서 발생한 실수나 시용자 영향에 의해 발생 </br></br> 두 개 모두 Throwable 클래스를 상속 받는다. Throwable 클래스에 getMessage()와 printStackTrace()가 구현되어 있다. |



</br>

## 5️⃣ 사용자 커스텀 예외

java에서 제공하는 예외 클래스 대신 Exception을 상속 받아서 사용자가 원하는 예외를 처리할 수 있다. 

```java

class CustomException extends Exception {
    private String msg;
	
    // 생성자
    public CustomException(String msg) {
        super(msg); 
        this.msg = msg;
    }
	
    // 메세지 출력
    public void printCustomMessage() {
        System.out.println(this.msg);
    }
}

public class Main {
    public static void main(String[] args) {
        try {
            throw new CustomException("CustomErrorMessage"); // throw를 통해 강제 Exception 발생
        } catch (CustomException e) {
            e.printMyMessage(); // 커스텀 예외 클래스의 메서드 실행
            e.printStackTrace(); // 상속한 부모 클래스 메서드 실행
        }
    }
}

```

</br>
